itcubesite/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as users_views
from users.forms import CustomAuthForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('became_teacher/', users_views.became_teacher),
    path('profile/', users_views.profile, name='profile'),
    path('register/', users_views.register, name='register'),
    path('became_secret_user/', users_views.became_secret),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html', authentication_form=CustomAuthForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('activate/<str:uidb64>/<str:token>/',
        users_views.activate, name='activate'),
     path('ss/bb/send_mails/', users_views.send_mails),
    path('', include('marathon.urls')),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

marathon/urls.py
from django.contrib import admin
from django.urls import path

from django.views.generic import RedirectView

from .views import (index, teachers, register_to_course, course_statistic, add_comment_to_course,
                    get_test_results)
from .views import (
    CourseView,
    CourseCreateView,
    CourseUpdateView,
    LessonView,
    LessonCreateView,
    LessonUpdateView,
)

urlpatterns = [
    path('', RedirectView.as_view(url='home'), name='home'),
    path('home', index),
    path('teachers', teachers, name='teachers'),
    path('course/<int:pk>', CourseView.as_view(), name='course'),
    path('addcoursecomment/', add_comment_to_course, name='add-comment-course'),
    path('course/<int:course_pk>/register', register_to_course, name='register-to-course'),
    path('course/<int:course_pk>/statistic', course_statistic, name='course-statistic'),
    path('course/<int:pk>/update/', CourseUpdateView.as_view(), name='course-update'),
    path('course/new/', CourseCreateView.as_view(), name='course-new'),
    path('lesson/<int:pk>', LessonView.as_view(), name='lesson'),
    path('lesson/<int:pk>/update', LessonUpdateView.as_view(), name='lesson-update'),
    path('course/<int:pk>/new_lesson', LessonCreateView.as_view(), name='lesson-new'),
    path('testresults/<int:pk>', get_test_results, name="test-results"),
]

marathon/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
#from tinymce.models import HTMLField
from testing.models import TestResult
from itcubesite.settings import MARATHON_START
import datetime

# Create your models here.
class Teacher(models.Model):
    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True)
    info = models.TextField(max_length=255)
    avatar = models.ImageField(null=True, blank=True)

    def __str__(self):
        return f"Учитель: {self.user.last_name} {self.user.first_name} "

class Course(models.Model):
    title = models.CharField(max_length=255)
    short_info = models.TextField(max_length=500, default='Краткая информация о курсе')
    info = models.TextField()
    you_tube_url = models.CharField(max_length=50, default='', blank=True, null=True)
    teacher = models.ForeignKey(Teacher, on_delete=models.SET_NULL, blank=True, null=True)
    secret_course = models.BooleanField(default=False)
    active = models.BooleanField(default=False)

    def __str__(self):
        return f'Направление: {self.title}'

    def get_published_lessons(self):
        return [lesson for lesson in self.lesson_set.order_by('order') if lesson.publish]

    def get_absolute_url(self):
        return reverse('course', kwargs={'pk':self.pk})

    def get_comments(self):
        return self.comments.all()


class Lesson(models.Model):
    title = models.CharField(max_length=255)
    #info = HTMLField()
    info = models.TextField()
    video = models.CharField(max_length=50, blank=True, null=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    order = models.IntegerField(default=0)

    @property
    def publish(self):
        return MARATHON_START + datetime.timedelta(days=self.order - 1) < datetime.datetime.now()

    @property
    def active(self):
        return MARATHON_START < datetime.datetime.now() < MARATHON_START + datetime.timedelta(days=self.order)

    class Meta:
        ordering = ['pk']

    def get_absolute_url(self):
        return reverse('lesson', kwargs={'pk':self.pk})

    def __str__(self):
        return f"Урок:{self.title}, курс: {self.course.title}"

class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True)
    info = models.TextField(max_length=255)
    courses = models.ManyToManyField(Course)
    secret_quest = models.BooleanField(default=False)
    age_category = models.ForeignKey("testing.AgeCategory", verbose_name="Возрастная категория", on_delete=models.CASCADE, null=True)

    def get_grades_for_course(self, course_pk):
        grades = {}
        for lesson in Course.objects.get(pk=course_pk).lesson_set.all():
            grades[lesson.id] = LessonMarks.objects.get_or_create(student=self, lesson=lesson)[0].value
        return grades

    def has_test(self, test):
        try:
            TestResult.objects.get(student=self, test=test)
            return True
        except TestResult.DoesNotExist:
            return False

    def get_test(self, test):
        if self.has_test(test):
            return TestResult.objects.get(student=self, test=test)
        else:
            return None

    def test_results(self, test):
        tr = self.get_test(test)
        if not tr:
            return None
        s = 0
        for resultanswer in tr.resultanswer_set.all():
            if resultanswer.selected_ans.right_ans:
                s += 1
            else:
                s -= 1
        return max(s, 0)

    def __str__(self):
        try:
            return f'Ученик: {self.user.last_name} {self.user.first_name}'
        except:
            return f'Ученик: {self.pk}'


class LessonMarks(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)
    value = models.IntegerField(default=0,
        validators=[
            MaxValueValidator(10),
            MinValueValidator(0)
        ])

class CourseComment(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField(max_length=300)
    created_on = models.DateField(auto_now_add=True)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return f"Комм. к {self.course.title} от {self.author.username}"
    

testing/models.py
from django.db import models
from django import forms

class AgeCategory(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        verbose_name = "AgeCategory"
        verbose_name_plural = "AgeCategorys"

    def __str__(self):
        return self.name


class Test(models.Model):
    name = models.CharField(max_length=50)
    lesson = models.ForeignKey('marathon.Lesson', verbose_name="tests", on_delete=models.CASCADE, null=True)
    category = models.ForeignKey(AgeCategory, verbose_name="category", on_delete=models.SET_NULL, null=True)

    class Meta:
        verbose_name = "Тест"
        verbose_name_plural = "Тесты"

    def __str__(self):
        return self.name


class Question(models.Model):
    text = models.TextField()
    test = models.ForeignKey(Test, verbose_name="test", on_delete=models.CASCADE)
    multiple = models.BooleanField(default=False)
    
    class Meta:
        verbose_name = "Вопрос"
        verbose_name_plural = "Вопросы"

    def __str__(self):
        return self.text

class Answer(models.Model):
    text = models.TextField()
    right_ans = models.BooleanField()
    question = models.ForeignKey(Question, verbose_name="answers", on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Ответ"
        verbose_name_plural = "Ответы"

    def __str__(self):
        return self.text


class TestResult(models.Model):
    test = models.ForeignKey(Test, verbose_name="test", on_delete=models.CASCADE)
    student = models.ForeignKey("marathon.Student", verbose_name="student", on_delete=models.CASCADE)

    class Meta:
        verbose_name = "TestResults"
        verbose_name_plural = "Test Resultss"


class ResultAnswer(models.Model):
    testresult = models.ForeignKey(TestResult, verbose_name="test_result", on_delete=models.CASCADE)
    selected_ans = models.ForeignKey(Answer, verbose_name="answer", on_delete=models.CASCADE)

    class Meta:
        verbose_name = "ResultAnswer"
        verbose_name_plural = "ResultAnswers"

marathon/forms.py
from django_summernote.widgets import SummernoteInplaceWidget
from django import forms
from .models import Lesson, Course

# If you don't like <iframe>, then use inplace widget
# Or if you're using django-crispy-forms, please use this.
class LessonForm(forms.ModelForm):
    class Meta:
        model = Lesson
        fields = ['title', 'info', 'video']
        widgets = {
            'info': SummernoteInplaceWidget(),
        }

class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['title', 'short_info', 'info', 'you_tube_url']
        widgets = {
            'info': SummernoteInplaceWidget(),
        }

marathon/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import user_passes_test
from django.contrib import messages
from django.core import serializers
from django.views.generic import (
    DetailView, 
    CreateView,
    UpdateView,
)
from .models import (
    Teacher,
    Student,
    Course,
    Lesson,
    CourseComment,
    LessonMarks
)
from .forms import LessonForm, CourseForm
from testing.models import *

# Create your views here.

def index(request):
    return render(request, 'index.html', context = {
                                            'tile':'Главная',
                                            'courses': Course.objects.filter(secret_course=False, active=True),
                                            'secret_courses': Course.objects.filter(secret_course=True, active=True),
                                            'teachers': Teacher.objects.all(),
                                        })


def teachers(request):
    return render(request, 'teachers.html', context = {'teachers': Teacher.objects.all()})

def check_student(user):
    try:
        if user.student:
            return True
    except:
        pass
    return False

def check_teacher(user):
    try:
        if user.teacher:
            return True
    except:
        pass
    return False


def add_comment_to_course(request):
    print(request)
    print(request.POST)
    data = request.POST
    print(data.get('body'))
    comment = CourseComment.objects.create(
        author = request.user,
        body = data.get('body'),
        course = Course.objects.get(pk=data.get('course'))
    )
    return JsonResponse(serializers.serialize('json', [comment]), safe=False)


@user_passes_test(check_student)
def register_to_course(request, course_pk):
    student = request.user.student
    course = Course.objects.get(pk=course_pk)
    student.courses.add(course)
    student.save()
    messages.success(request,f"Вы успешно записались на курс '{course.title}'!")
    return redirect('course', pk=course.pk)

@user_passes_test(check_teacher)
def course_statistic(request, course_pk):
    course = Course.objects.get(pk=course_pk)
    return render(request, 'marathon/course_statistic.html', context={'course': course})

def get_test_results(request, pk):
    test = Test.objects.get(pk=pk)
    tr, _ = TestResult.objects.update_or_create(test=test, student=request.user.student)
    for question in test.question_set.all():
        if question.multiple:
            ans_list = request.POST.getlist(str(question.pk))
            if ans_list[0] != [0]:
                for ans in ans_list:
                    ResultAnswer.objects.update_or_create(testresult=tr, 
                                                selected_ans=Answer.objects.get(pk=int(ans)))
        else:
            ans = int(request.POST.getlist(str(question.pk), [0])[0])
            if ans != 0:
                ResultAnswer.objects.update_or_create(testresult=tr, 
                                                selected_ans=Answer.objects.get(pk=ans))
    return redirect('lesson', pk=test.lesson.pk)



class CourseView(DetailView):
    model = Course
    

class CourseCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Course
    form_class = CourseForm

    def form_valid(self, form):
        form.instance.teacher = self.request.user.teacher
        return super().form_valid(form)

    def test_func(self):
        try:
            if self.request.user.teacher:
                return True
        except:
            return False


class CourseUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Course
    form_class = CourseForm

    def form_valid(self, form):
        form.instance.teacher = self.request.user.teacher
        return super().form_valid(form)

    def test_func(self):
        try:
            teacher = self.request.user.teacher
        except:
            return False
        return teacher == self.get_object().teacher


class LessonView(DetailView):
    model = Lesson

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            student = self.request.user.student
            if student.age_category:
                lesson = self.get_object()
                test = lesson.test_set.get(lesson=lesson,
                                                      category=student.age_category)
                
            else:
                test = lesson.test_set.first()
            context['test'] = test
            context['already_done_test'] = student.has_test(test)
            context['test_result'] = student.test_results(test)
        except:
            pass
        print(context)
        return context
    



class LessonCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Lesson
    form_class = LessonForm

    def form_valid(self, form):
        course = Course.objects.get(pk=self.kwargs.get('pk'))
        form.instance.course = course
        return super().form_valid(form)

    def test_func(self):
        try:
            teacher = self.request.user.teacher
        except:
            return False
        course = Course.objects.get(pk=self.kwargs.get('pk'))
        return teacher == course.teacher


class LessonUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Lesson
    form_class = LessonForm

    def form_valid(self, form):
        course = self.get_object().course
        form.instance.course = course
        return super().form_valid(form)

    def test_func(self):
        try:
            teacher = self.request.user.teacher
        except:
            return False
        course = self.get_object().course
        return teacher == course.teacher

marathon/templates/marathon/course_detail.html
{% extends 'base.html'%}
{% block content%}
    <div class="d-flex justify-content-center">
        <h1>{{course.title}}</h1>
    </div>



    {% if course.you_tube_url %}
    <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="https://youtube.com/embed/{{course.you_tube_url}}" allowfullscreen></iframe>
    </div>
    {% endif %}

    <div class="d-flex flex-column justify-content-center mt-3">
        <p>{{course.info|safe}}</p>
    </div>

    {% if user.teacher == course.teacher%}
         <a href="{% url 'course-statistic' course.pk%}" class="btn btn-primary">Посмтреть статистику курса</a>
         <a href="{% url 'course-update' course.pk%}" class="btn btn-danger">Редактировать</a>
         <a href="{% url 'lesson-new' course.pk%}" class="btn btn-secondary">Добавить урок</a>
    {% endif %}

    {% if user.student and course not in user.student.courses.all %}
        <a href="{% url 'register-to-course' course.pk%}" class="btn btn-primary">Записаться на курс</a>
    {% endif %}

    {% if course in user.student.courses.all or not user.student%}
        {% for lesson in course.get_published_lessons %}
            <div class="card">
                <div class="card-header" id="headingOne">
                <h2 class="mb-0">
                    <button class="btn btn-link" type="button">
                        <a class="nav-link" href="{% url 'lesson' lesson.pk %}">{{lesson.title}}</a>
                    </button>
                </h2>
                </div>

            </div>
        {% endfor %}
    {% endif %}
    <h3>Комментарии:</h3>
    {% for comment in course.get_comments %}
        <div class="container my-3">
            <div class="row">
                <div class="col-8">
                    <div class="card card-white post">
                        <div class="post-heading">
                            <div class="float-left meta">
                                <div class="title h5">
                                    <a href="#"><b>{{comment.author}}</b></a>
                                    оставил комментарий.
                                </div>
                                <h6 class="text-muted time">{{comment.created_on}}</h6>
                            </div>
                        </div> 
                        <div class="post-description"> 
                            <p>{{comment.body}}</p>

                        </div>
                    </div>
                </div>
                
            </div>
        </div>
    {% endfor %}
    <div class="container my-3 d-flex flex-column ">
        <textarea id="new_comment" class="w-50" style="height:100px;" placeholder="{% if request.user.is_authenticated %}Оставьте комментарий {% else %} Только зарегестрированные пользователи могу оставлять комментарии{% endif %}"></textarea>
        {% if request.user.is_authenticated %}
        <button id="submit_comment" type="button" class="btn btn-success w-50 mt-3">Отправить</button>
        {% endif %}
    </div>
    <script type="text/javascript">
    $("#submit_comment").click(function(){  
        $.ajax({
        type: "POST",
        url : "{% url 'add-comment-course'%}",
         data : {
            course: {{course.pk}},
            body: $('textarea#new_comment').val(),
            csrfmiddlewaretoken: '{{ csrf_token }}',
         },
         success: function(data, status, xhr){
            location.reload();
        }
        });
        return false;
    });
</script>
    

{% endblock%}

marathon/templates/marathon/course_form.html
{% extends "base.html" %}

{% block extra %}

<script src="https://code.jquery.com/jquery-3.5.0.js" integrity="sha256-r/AaFHrszJtwpe+tHyNi/XCfMxYpbsRg2Uqn0x3s2zc=" crossorigin="anonymous"></script>
{{form.media}}
    <style>
      @font-face {
            font-family: "summernote";
            font-style: normal;
            font-weight: normal;
            src: url("https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/font/summernote.eot");
            src: url("https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/font/summernote.eot") format("embedded-opentype"),
            url("https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/font/summernote.woff") format("woff"),
            url("https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/font/summernote.ttf") format("truetype");
        }
    </style>
{% endblock %}

{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Новый курс</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit"> Готово</button>
            </div>
        </form>
    </div>
   <script>
    $(document).ready(function() {
        $('#summernote').summernote();
    });
  </script>
{% endblock content %}

marathon/templates/marathon/course_statistic.html
{% extends 'base.html'%}
{% block content%}
    <div class="d-flex justify-content-center">
        <h1>{{course.title}}</h1>
    </div>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Логин</th>
      <th scope="col">Имя</th>
      <th scope="col">Фамилия</th>
      {% for lesson in course.lesson_set.all%}
        <th scope="col">{{lesson.title}}</th>
      {% endfor %}
    </tr>
  </thead>
  <tbody>
    {%for student in course.student_set.all%}
    <tr>
      <th contenteditable='true' scope="row">{{forloop.counter}}</th>
      <td>{{student.user.username}}</td>
      <td>{{student.user.firstname}}</td>
      <td>{{student.user.lastname}}</td>
      {% for grade in course.lesson_set.all%}
        <th scope="col">{{lesson.title}}</th>
      {% endfor %}
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock%}

marathon/templates/marathon/lesson_detail.html
{% extends 'base.html'%}
{% block content%}

    <a class="nav-link" href="{% url 'course' lesson.course.pk %}">К курсу</a>
    <div class="d-flex justify-content-center">
        <h1>{{lesson.title}}</h1>
    </div>

    {% if lesson.video %}
    <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="https://youtube.com/embed/{{lesson.video}}" allowfullscreen></iframe>
    </div>
    {% endif %}

    <div class="d-flex flex-column justify-content-center mt-3">
        {{lesson.info|safe}}
    </div>

    {% if user.teacher and lesson.course.teacher == user.teacher%}
        <a href="{% url 'lesson-update' lesson.pk%}" class="btn btn-danger">Редактировать</a>
    {% endif %}
    <a class="nav-link" href="{% url 'course' lesson.course.pk %}">К курсу</a>

    {% if lesson.active %}
    <h1> Урок активен </h1>
    {% if user.student and test%}
        {% if not already_done_test %}
        <form action="{% url 'test-results' test.pk %}" target="result" method="post">
            <h1> {{test.name}}</h1>
            {% csrf_token %}
            {% for question in test.question_set.all %}
                <h2>{{question.text}}</h2>
                {% for answer in question.answer_set.all %}
                    {% if question.multiple %}
                        <input type="checkbox" id="question{{question.pk}}-{{answer.pk}}" name="{{question.pk}}" value="{{answer.pk}}">
                    {% else %}
                        <input type="radio" id="question{{question.pk}}-{{answer.pk}}" name="{{question.pk}}" value="{{answer.pk}}">
                    {% endif %}
                    <label for="question{{question.pk}}-{{answer.pk}}">{{answer.text}}</label><br>
                {% endfor %}

            {% endfor %}
            <p><input type="submit" value="Submit"></p>
        </form>
        {% else %}
        <h1> Вы уже сдавали тест, ваш результат: {{test_result}}</h1>
        {% endif %}

    {% endif %}
    {% endif %}
{% endblock%}

marathon/templates/marathon/lesson_form.html
{% extends "base.html" %}
{%block extra%}
<script src="https://code.jquery.com/jquery-3.5.0.js" integrity="sha256-r/AaFHrszJtwpe+tHyNi/XCfMxYpbsRg2Uqn0x3s2zc=" crossorigin="anonymous"></script>
{{form.media}}
<style>
      @font-face {
            font-family: "summernote";
            font-style: normal;
            font-weight: normal;
            src: url("https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/font/summernote.eot");
            src: url("https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/font/summernote.eot") format("embedded-opentype"),
            url("https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/font/summernote.woff") format("woff"),
            url("https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/font/summernote.ttf") format("truetype");
        }
    </style>
{%endblock%}


{% load crispy_forms_tags %}
{% block content %}

    <div class="content-section">
        <form method="POST">
           
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Новый урок</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit"> Готово</button>
            </div>
        </form>
    </div>

<script>
    $(document).ready(function() {
        $('#summernote').summernote();
    });
  </script>
{% endblock content %}