itcubesite/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as users_views
from users.forms import CustomAuthForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('became_teacher/', users_views.became_teacher),
    path('profile/', users_views.profile, name='profile'),
    path('register/', users_views.register, name='register'),
    path('became_secret_user/', users_views.became_secret),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html', authentication_form=CustomAuthForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('activate/<str:uidb64>/<str:token>/',
        users_views.activate, name='activate'),
     path('ss/bb/send_mails/', users_views.send_mails),
    path('', include('marathon.urls')),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

marathon/urls.py
from django.contrib import admin
from django.urls import path

from django.views.generic import RedirectView

from .views import (index, teachers, register_to_course, course_statistic, add_comment_to_course,
                    get_test_results)
from .views import (
    CourseView,
    CourseCreateView,
    CourseUpdateView,
    LessonView,
    LessonCreateView,
    LessonUpdateView,
)

urlpatterns = [
    path('', RedirectView.as_view(url='home'), name='home'),
    path('home', index),
    path('teachers', teachers, name='teachers'),
    path('course/<int:pk>', CourseView.as_view(), name='course'),
    path('addcoursecomment/', add_comment_to_course, name='add-comment-course'),
    path('course/<int:course_pk>/register', register_to_course, name='register-to-course'),
    path('course/<int:course_pk>/statistic', course_statistic, name='course-statistic'),
    path('course/<int:pk>/update/', CourseUpdateView.as_view(), name='course-update'),
    path('course/new/', CourseCreateView.as_view(), name='course-new'),
    path('lesson/<int:pk>', LessonView.as_view(), name='lesson'),
    path('lesson/<int:pk>/update', LessonUpdateView.as_view(), name='lesson-update'),
    path('course/<int:pk>/new_lesson', LessonCreateView.as_view(), name='lesson-new'),
    path('testresults/<int:pk>', get_test_results, name="test-results"),
]

marathon/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
#from tinymce.models import HTMLField
from testing.models import TestResult
from itcubesite.settings import MARATHON_START
import datetime

# Create your models here.
class Teacher(models.Model):
    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True)
    info = models.TextField(max_length=255)
    avatar = models.ImageField(null=True, blank=True)

    def __str__(self):
        return f"Учитель: {self.user.last_name} {self.user.first_name} "

class Course(models.Model):
    title = models.CharField(max_length=255)
    short_info = models.TextField(max_length=500, default='Краткая информация о курсе')
    info = models.TextField()
    you_tube_url = models.CharField(max_length=50, default='', blank=True, null=True)
    teacher = models.ForeignKey(Teacher, on_delete=models.SET_NULL, blank=True, null=True)
    secret_course = models.BooleanField(default=False)
    active = models.BooleanField(default=False)

    def __str__(self):
        return f'Направление: {self.title}'

    def get_published_lessons(self):
        return [lesson for lesson in self.lesson_set.order_by('order') if lesson.publish]

    def get_absolute_url(self):
        return reverse('course', kwargs={'pk':self.pk})

    def get_comments(self):
        return self.comments.all()


class Lesson(models.Model):
    title = models.CharField(max_length=255)
    #info = HTMLField()
    info = models.TextField()
    video = models.CharField(max_length=50, blank=True, null=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    order = models.IntegerField(default=0)

    @property
    def publish(self):
        return MARATHON_START + datetime.timedelta(days=self.order - 1) < datetime.datetime.now()

    @property
    def active(self):
        return MARATHON_START < datetime.datetime.now() < MARATHON_START + datetime.timedelta(days=self.order)

    class Meta:
        ordering = ['pk']

    def get_absolute_url(self):
        return reverse('lesson', kwargs={'pk':self.pk})

    def __str__(self):
        return f"Урок:{self.title}, курс: {self.course.title}"

class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True)
    info = models.TextField(max_length=255)
    courses = models.ManyToManyField(Course)
    secret_quest = models.BooleanField(default=False)
    age_category = models.ForeignKey("testing.AgeCategory", verbose_name="Возрастная категория", on_delete=models.CASCADE, null=True)

    def get_grades_for_course(self, course_pk):
        grades = {}
        for lesson in Course.objects.get(pk=course_pk).lesson_set.all():
            grades[lesson.id] = LessonMarks.objects.get_or_create(student=self, lesson=lesson)[0].value
        return grades

    def has_test(self, test):
        try:
            TestResult.objects.get(student=self, test=test)
            return True
        except TestResult.DoesNotExist:
            return False

    def get_test(self, test):
        if self.has_test(test):
            return TestResult.objects.get(student=self, test=test)
        else:
            return None

    def test_results(self, test):
        tr = self.get_test(test)
        if not tr:
            return None
        s = 0
        for resultanswer in tr.resultanswer_set.all():
            if resultanswer.selected_ans.right_ans:
                s += 1
            else:
                s -= 1
        return max(s, 0)

    def __str__(self):
        try:
            return f'Ученик: {self.user.last_name} {self.user.first_name}'
        except:
            return f'Ученик: {self.pk}'


class LessonMarks(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)
    value = models.IntegerField(default=0,
        validators=[
            MaxValueValidator(10),
            MinValueValidator(0)
        ])

class CourseComment(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField(max_length=300)
    created_on = models.DateField(auto_now_add=True)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return f"Комм. к {self.course.title} от {self.author.username}"
    

templates/acc_active_email.html
{% autoescape off %}
Здравствуй {{ user.username }},
для завершения регистрации осталось только перейти по данной ссылке!
http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    {% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
   
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">   
    <link rel="stylesheet" href="{% static 'css/carousel.css' %}">  
    {% block extra %}
    {% endblock %}
    
    <title>{{ title }}</title>
  </head>
  <body>
  <nav class="navbar navbar-expand-lg navbar-light" style="background-color:#D8D8D8;">

    <div id="menu" class="navbar-collapse collapse w-100 dual-collapse2 order-1 order-md-2">
        <ul class="navbar-nav mx-auto text-center">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'home' %}">Главная</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}#napr">Направления</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}#teachers">Педагоги</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}#about">Об IT-Cube</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}#contacts">Контакты</a>
            </li>
        </ul>
    </div>
    <div class="navbar-collapse collapse w-100 dual-collapse2 order-3 order-md-2">
        <ul class="navbar-nav ml-auto text-center">
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'profile' %}">{{ user.username }}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Выйти</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Войти</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'register' %}">Регистрация</a>
            </li>
            {%endif%}
        </ul>
    </div>
</nav>
{% block index %}
    
 {% endblock index %}
 
 <div class='row mt-5 mb-5'>
        <div class='container justify-content-center'>
            {%if messages%}
                {%for message in messages %}
                    <div class="alert alert-{{message.tags}}">
                        {{message}}
                    </div>
                {%endfor%}
            {%endif%}
    {% block content %}
    {% endblock content %}
        </div>
    </div>
    <footer class="footer">
         <div class="img__container mt-0 mb-0">
             <img src="{% static 'images/Resurs_9.png' %}" class="image" alt="Описание изображения...">
        </div>
    </footer>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
   <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</body>
</html>

templates/student.html
<h3>Мои курсы</h3>
<div class="accordion" id="courseExpanded">
{% for course in user.student.courses.all%}
    <div class="card">
    <div class="card-header" id="headingOne">
      <h2 class="mb-0">
        <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseCourse{{course.pk}}" aria-expanded="true" aria-controls="collapseOne">
          {{course.title}}
        </button>
      </h2>
    </div>

    <div id="collapseCourse{{course.pk}}" class="collapse" aria-labelledby="headingOne" data-parent="#courseExpanded">
      <div class="card-body inline">
        <p class="card-text">{{course.short_info}}</p>
        <a href="{% url 'course' course.pk%}" class="btn btn-primary">Перейти к направлению</a>
      </div>
    </div>
  </div>
{% endfor %}
</div>

templates/teacher.html
<h3>Мои курсы</h3>
<a href="{% url 'course-new'%}" class="btn btn-primary">Создать курс</a>

<div class="accordion" id="courseExpanded">
{% for course in user.teacher.course_set.all%}
    <div class="card">
    <div class="card-header" id="headingOne">
      <h2 class="mb-0">
        <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseCourse{{course.pk}}" aria-expanded="true" aria-controls="collapseOne">
          {{course.title}}
        </button>
      </h2>
    </div>

    <div id="collapseCourse{{course.pk}}" class="collapse" aria-labelledby="headingOne" data-parent="#courseExpanded">
      <div class="card-body inline">
        <p class="card-text">{{course.short_info}}</p>
        <a href="{% url 'course' course.pk%}" class="btn btn-primary">Перейти к направлению</a>
      </div>
    </div>
  </div>
{% endfor %}
</div>

templates/teachers.html
{% extends "base.html" %}
{% block content %}
   <h1> Наши педагоги</h1>

    {% for teacher in teachers%}
        <div class="card mb-3" style="max-width: 540px;">
            <div class="row no-gutters">
                <div class="col-md-4">
                <img src="{% if teacher.avatar %}{{teacher.avatar.url}} {% endif %}" class="card-img" alt="...">
                </div>
                <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">{{teacher.user.last_name}} {{teacher.user.first_name}}</h5>
                    <p class="card-text">Какой-то текст про педагога и все такое.</p>
                </div>
                </div>
            </div>
            </div>
    {% endfor %}
{% endblock content %}